version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: aplcorp-postgres
    environment:
      POSTGRES_DB: aplcorp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: aplcorp-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aplcorp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "19000:8080"
      - "19007:8787"
    restart: always
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
