CREATE TABLE IF NOT EXISTS usuario (
    cpf VARCHAR(11) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    data_nasc DATE NOT NULL,
    data_cad DATE NOT NULL,
    ativo BOOLEAN NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);